name = "Oxocarbon Dark"
type = "dark"

[colors]
foreground = "#f2f4f8"
focusBorder = "#262626"
errorForeground = "#ee5396"
disabledForeground = "#8d8d8d"

"selection.background" = "#6f6f6f"
"sash.hoverBorder" = "#525252"
"simpleFindWidget.sashBorder" = "#262626"

"button.background" = "#393939"
"button.hoverBackground" = "#525252"

"welcomePage.progress.background" = "#393939"
"welcomePage.progress.foreground" = "#525252"
"textLink.foreground" = "#ff7eb6"
"textLink.activeForeground" = "#be95ff"

"editor.background" = "#161616"
"editor.foreground" = "#f2f4f8"
"editor.inactiveSelectionBackground" = "#39393920"
"editor.selectionBackground" = "#393939"
"editor.selectionHighlightBackground" = "#52525290"
"editor.findMatchBackground" = "#3ddbd999"
"editor.findMatchForeground" = "#ffffff"
"editor.findMatchHighlightBackground" = "#39393999"
"editor.snippetTabstopHighlightBackground" = "#393939"
"editor.snippetFinalTabstopHighlightBackground" = "#525252"
"editor.snippetTabstopHighlightBorder" = "#ff7eb6"
"editor.snippetFinalTabstopHighlightBorder" = "#ee5396"

"editorCursor.foreground" = "#ffffff"
"editorLink.activeForeground" = "#ff7eb6"
"editorInlayHint.foreground" = "#878d96"
"editorInlayHint.background" = "#00000000"
"editorGroup.border" = "#262626"
"editorGroup.dropBackground" = "#39393940"
"editorGroupHeader.tabsBorder" = "#262626"
"editorGroupHeader.tabsBackground" = "#262626"
"editorRuler.foreground" = "#262626"

"editorError.foreground" = "#ee5396"
"editorWarning.foreground" = "#ff7eb6"
"editorInfo.foreground" = "#ff7eb6"
"editorHint.foreground" = "#dde1e6"
"editorLightBulb.foreground" = "#ffffff"

"editorGutter.addedBackground" = "#42be65"
"editorGutter.modifiedBackground" = "#08bdba"
"editorGutter.deletedBackground" = "#ee5396"

"editorOverviewRuler.background" = "#00000000"
"editorOverviewRuler.border" = "#262626"
"editorOverviewRuler.findMatchForeground" = "#3ddbd999"
"editorOverviewRuler.rangeHighlightForeground" = "#39393999"
"editorOverviewRuler.selectionHighlightForeground" = "#52525220"
"editorOverviewRuler.addedForeground" = "#42be65"
"editorOverviewRuler.modifiedForeground" = "#08bdba"
"editorOverviewRuler.deletedForeground" = "#ee5396"
"editorOverviewRuler.errorForeground" = "#ee5396"
"editorOverviewRuler.warningForeground" = "#ff7eb6"
"editorOverviewRuler.infoForeground" = "#dde1e6"
"editorOverviewRuler.bracketMatchForeground" = "#6f6f6f"
"editorOverviewRuler.inlineChatInserted" = "#42be65"
"editorOverviewRuler.inlineChatRemoved" = "#ee5396"
"editorOverviewRuler.currentContentForeground" = "#ff7eb6"
"editorOverviewRuler.incomingContentForeground" = "#08bdba"

"scmGraph.foreground1" = "#ff7eb6"
"scmGraph.foreground2" = "#3ddbd9"
"scmGraph.foreground3" = "#ee5396"
"scmGraph.foreground4" = "#33b1ff"
"scmGraph.foreground5" = "#08bdba"
"scmGraph.historyItemBaseRefColor" = "#78a9ff"
"scmGraph.historyItemHoverAdditionsForeground" = "#42be65"
"scmGraph.historyItemHoverDefaultLabelBackground" = "#393939"
"scmGraph.historyItemHoverDefaultLabelForeground" = "#f2f4f8"
"scmGraph.historyItemHoverDeletionsForeground" = "#ee5396"
"scmGraph.historyItemHoverLabelForeground" = "#f2f4f8"
"scmGraph.historyItemRefColor" = "#ee5396"
"scmGraph.historyItemRemoteRefColor" = "#525252"

# cursor accept color ??
"charts.green" = "#42be65"

# may as well do the rest
"chart.axis" = "#262626"
"chart.guide" = "#262626"
"chart.line" = "#262626"
"charts.lines" = "#f2f4f8"
"charts.foreground" = "#f2f4f8"
"charts.blue" = "#ff7eb6"
"charts.orange" = "#3ddbd9"
"charts.purple" = "#be95ff"
"charts.red" = "#ee5396"
"charts.yellow" = "#33b1ff"

"widget.border" = "#262626"
"widget.shadow" = "#00000080"
"editorWidget.foreground" = "#dde1e6"
"editorWidget.background" = "#1b1b1b"
"editorWidget.border" = "#262626"
"editorWidget.resizeBorder" = "#525252"

"editorSuggestWidget.background" = "#1b1b1b"
"editorSuggestWidget.border" = "#00000000"
"editorSuggestWidget.foreground" = "#dde1e6"
"editorSuggestWidget.highlightForeground" = "#ffffff"
"editorSuggestWidget.focusHighlightForeground" = "#ff7eb6"
"editorSuggestWidget.selectedBackground" = "#393939"
"editorSuggestWidget.selectedForeground" = "#ffffff"
"editorSuggestWidget.selectedIconForeground" = "#ffffff"

"editorHoverWidget.background" = "#1b1b1b"
"editorHoverWidget.border" = "#262626"
"editorHoverWidget.foreground" = "#dde1e6"

"editorGhostText.border" = "#262626"
"editorGhostText.background" = "#00000000"
"editorGhostText.foreground" = "#525252"

"editorStickyScroll.border" = "#262626"
"editorStickyScroll.shadow" = "#00000080"
"editorStickyScrollHover.background" = "#393939"

"editor.wordHighlightBackground" = "#26262630"
"editor.wordHighlightBorder" = "#00000000"

"editorBracketHighlight.foreground1" = "#8d8d8d"
"editorBracketHighlight.foreground2" = "#6f6f6f"
"editorBracketHighlight.foreground3" = "#8d8d8d"
"editorBracketHighlight.foreground4" = "#6f6f6f"
"editorBracketHighlight.foreground5" = "#8d8d8d"
"editorBracketHighlight.foreground6" = "#6f6f6f"
"editorBracketHighlight.unexpectedBracket.foreground" = "#ee5396"

"editorMarkerNavigation.background" = "#1b1b1b"
"editorMarkerNavigationError.background" = "#ee5396"
"editorMarkerNavigationWarning.background" = "#ff7eb6"
"editorMarkerNavigationInfo.background" = "#08bdba"

"problemsErrorIcon.foreground" = "#ee5396"
"problemsWarningIcon.foreground" = "#ff7eb6"
"problemsInfoIcon.foreground" = "#be95ff"

"peekView.border" = "#262626"
"peekViewEditor.background" = "#1b1b1b"
"peekViewEditor.matchHighlightBackground" = "#525252"
"peekViewResult.background" = "#212121"
"peekViewResult.lineForeground" = "#dde1e6"
"peekViewResult.matchHighlightBackground" = "#6F6F6F"
"peekViewResult.selectionBackground" = "#393939"
"peekViewResult.selectionForeground" = "#ffffff"

"diffEditor.diagonalFill" = "#525252"
"diffEditor.insertedLineBackground" = "#42be6520"
"diffEditor.insertedTextBackground" = "#42be6540"
"diffEditor.removedLineBackground" = "#ee539620"
"diffEditor.removedTextBackground" = "#ee539640"
"diffEditorGutter.insertedLineBackground" = "#42be6520"
"diffEditorGutter.removedLineBackground" = "#ee539620"

"gitDecoration.addedResourceForeground" = "#42be65"
"gitDecoration.modifiedResourceForeground" = "#ff7eb6"
"gitDecoration.deletedResourceForeground" = "#ee5396"
"gitDecoration.ignoredResourceForeground" = "#8d8d8d"
"gitDecoration.renamedResourceForeground" = "#a6c8ff"
"gitDecoration.untrackedResourceForeground" = "#c1c7cd"
"gitDecoration.stageDeletedResourceForeground" = "#ee5396"
"gitDecoration.stageModifiedResourceForeground" = "#08bdba"

"input.background" = "#262626"
"input.foreground" = "#dde1e6"
"inputOption.hoverBackground" = "#52525290"
"inputOption.activeBackground" = "#52525290"
"inputOption.activeBorder" = "#525252"
"inputOption.activeForeground" = "#ffffff"

"titleBar.border" = "#262626"
"titleBar.activeBackground" = "#161616"
"titleBar.inactiveBackground" = "#262626"

"tab.hoverBackground" = "#262626"
"tab.activeBackground" = "#161616"
"tab.activeForeground" = "#ffffff"
"tab.inactiveBackground" = "#262626"
"tab.inactiveForeground" = "#8d8d8d"
"tab.unfocusedInactiveForeground" = "#8d8d8d"

"tab.border" = "#161616"
"tab.activeBorder" = "#161616"
"tab.activeBorderTop" = "#ff7eb6"
"tab.unfocusedActiveBorder" = "#161616"
"tab.unfocusedActiveBorderTop" = "#262626"
"tab.dragAndDropBorder" = "#ff7eb6"

"activityBar.background" = "#161616"
"activityBar.foreground" = "#f2f4f8"
"activityBar.border" = "#262626"
"activityBar.activeBorder" = "#ff7eb6"
"activityBar.dropBorder" = "#393939"
"activityBarBadge.background" = "#525252"
"activityBarBadge.foreground" = "#f2f4f8"

"sideBar.background" = "#161616"
"sideBar.dropBackground" = "#36363640"
"sideBar.border" = "#262626"
"sideBarTitle.foreground" = "#ffffff"
"sideBarSectionHeader.background" = "#393939"

"statusBar.background" = "#161616"
"statusBar.foreground" = "#dde1e6"
"statusBar.border" = "#262626"
"statusBar.debuggingBackground" = "#0f62fe"
"statusBar.debuggingForeground" = "#ffffff"
"statusBar.noFolderBackground" = "#0f62fe"
"statusBar.noFolderForeground" = "#ffffff"
"statusBarItem.remoteBackground" = "#0f62fe"
"statusBarItem.remoteForeground" = "#ffffff"
"statusBarItem.errorBackground" = "#00000000"
"statusBarItem.errorForeground" = "#ee5396"
"statusBarItem.warningBackground" = "#00000000"
"statusBarItem.warningForeground" = "#ee5396"

"list.activeSelectionBackground" = "#393939"
"list.activeSelectionForeground" = "#ffffff"
"list.activeSelectionIconForeground" = "#ffffff"
"list.dropBackground" = "#52525240"
"list.focusBackground" = "#393939"
"list.focusForeground" = "#ffffff"
"list.focusHighlightForeground" = "#ff7eb6"
"list.focusOutline" = "#262626"
"list.focusAndSelectionOutline" = "#262626"
"list.highlightForeground" = "#ffffff"
"list.hoverBackground" = "#52525220"
"list.hoverForeground" = "#ffffff"
"list.inactiveSelectionBackground" = "#262626"
"list.inactiveSelectionForeground" = "#dde1e6"
"list.inactiveSelectionIconForeground" = "#dde1e6"
"list.inactiveFocusBackground" = "#262626"
"list.inactiveFocusOutline" = "#00000000"
"list.invalidItemForeground" = "#ee5396"
"list.errorForeground" = "#ee5396"
"list.warningForeground" = "#ff7eb6"
"list.filterMatchBackground" = "#ff7eb650"
"list.filterMatchBorder" = "#ff7eb600"
"list.deemphasizedForeground" = "#6f6f6f"
"list.dropBetweenBackground" = "#525252"
"listFilterWidget.background" = "#262626"
"listFilterWidget.outline" = "#525252"
"listFilterWidget.noMatchesOutline" = "#ee5396"
"listFilterWidget.shadow" = "#00000080"

"tree.indentGuidesStroke" = "#525252"
"tree.inactiveIndentGuidesStroke" = "#262626"
"tree.tableColumnsBorder" = "#262626"
"tree.tableOddRowsBackground" = "#212121"

"panel.background" = "#161616"
"panel.border" = "#262626"
"panelTitle.border" = "#00000000"
"panelTitle.activeBorder" = "#ff7eb6"
"panelTitle.activeForeground" = "#ffffff"
"panelSection.border" = "#262626"
"panelSection.dropBackground" = "#39393940"

"notifications.background" = "#262626"
"notificationCenterHeader.background" = "#262626"

"checkbox.background" = "#262626"
"checkbox.border" = "#262626"
"checkbox.foreground" = "#ffffff"
"checkbox.selectBackground" = "#393939"
"checkbox.selectBorder" = "#525252"

"notebook.cellBorderColor" = "#262626"
"notebook.focusedCellBorder" = "#ff7eb6"
"notebook.cellEditorBackground" = "#1b1b1b"
"notebook.cellStatusBarItemHoverBackground" = "#393939"
"notebook.outputContainerBackgroundColor" = "#181818"

"debugIcon.breakpointForeground" = "#ee5396"
"debugIcon.breakpointDisabledForeground" = "#525252"
"debugIcon.breakpointUnverifiedForeground" = "#ff7eb6"
"debugIcon.breakpointCurrentStackframeForeground" = "#08bdba"
"debugIcon.breakpointStackframeForeground" = "#78a9ff"
"debugIcon.startForeground" = "#ffffff"
"debugIcon.pauseForeground" = "#ffffff"
"debugIcon.stopForeground" = "#ffffff"
"debugIcon.disconnectForeground" = "#c1c7cd"
"debugIcon.restartForeground" = "#ffffff"
"debugIcon.stepOverForeground" = "#ffffff"
"debugIcon.stepIntoForeground" = "#ffffff"
"debugIcon.stepOutForeground" = "#ffffff"
"debugIcon.continueForeground" = "#ffffff"
"debugIcon.stepBackForeground" = "#ffffff"

"debugConsole.infoForeground" = "#dde1e6"
"debugConsole.warningForeground" = "#ff7eb6"
"debugConsole.errorForeground" = "#ee5396"
"debugConsole.sourceForeground" = "#82cfff"
"debugConsoleInputIcon.foreground" = "#ff7eb6"

"testing.iconFailed" = "#ee5396"
"testing.iconErrored" = "#ee5396"
"testing.iconPassed" = "#42be65"
"testing.iconSkipped" = "#ff7eb6"
"testing.runAction" = "#08bdba"

"gauge.background" = "#262626"
"gauge.foreground" = "#42be65"
"gauge.border" = "#393939"
"gauge.warningBackground" = "#262626"
"gauge.warningForeground" = "#ff7eb6"
"gauge.errorBackground" = "#262626"
"gauge.errorForeground" = "#ee5396"

"minimap.findMatchHighlight" = "#ee539650"
"minimap.selectionHighlight" = "#39393950"
"minimap.errorHighlight" = "#ee539650"
"minimap.warningHighlight" = "#ff7eb650"
"minimap.infoHighlight" = "#dde1e650"
"minimapGutter.addedBackground" = "#42be6520"
"minimapGutter.modifiedBackground" = "#08bdba20"
"minimapGutter.deletedBackground" = "#ee539620"

"keybindingLabel.background" = "#262626"
"keybindingLabel.foreground" = "#dde1e6"
"keybindingLabel.border" = "#525252"

"textPreformat.background" = "#262626"
"textPreformat.foreground" = "#f2f4f8"
"textCodeBlock.background" = "#1b1b1b"
"textBlockQuote.background" = "#1b1b1b"
"textBlockQuote.border" = "#ff7eb6"

"pickerGroup.border" = "#393939"
"pickerGroup.foreground" = "#ff7eb6"

"banner.background" = "#1b1b1b"
"banner.foreground" = "#dde1e6"

"menu.background" = "#262626"
"menu.foreground" = "#dde1e6"
"menu.selectionBackground" = "#393939"
"menu.selectionForeground" = "#ffffff"
"menu.separatorBackground" = "#525252"
"menu.border" = "#262626"

"settings.modifiedItemIndicator" = "#ff7eb6"

"terminal.border" = "#262626"
"terminal.background" = "#161616"
"terminal.foreground" = "#ffffff"
"terminal.ansiBlack" = "#161616"
"terminal.ansiRed" = "#78a9ff"
"terminal.ansiGreen" = "#ff7eb6"
"terminal.ansiYellow" = "#42be65"
"terminal.ansiBlue" = "#08bdba"
"terminal.ansiMagenta" = "#82cfff"
"terminal.ansiCyan" = "#33b1ff"
"terminal.ansiWhite" = "#dde1e6"
"terminal.ansiBrightBlack" = "#525252"
"terminal.ansiBrightRed" = "#78a9ff"
"terminal.ansiBrightGreen" = "#ff7eb6"
"terminal.ansiBrightYellow" = "#42be65"
"terminal.ansiBrightBlue" = "#08bdba"
"terminal.ansiBrightMagenta" = "#82cfff"
"terminal.ansiBrightCyan" = "#33b1ff"
"terminal.ansiBrightWhite" = "#ffffff"
"terminal.selectionBackground" = "#393939"
"terminal.selectionForeground" = "#ffffff"
"terminal.inactiveSelectionBackground" = "#39393940"
"terminal.findMatchBackground" = "#3ddbd999"
"terminal.findMatchBorder" = "#00000000"
"terminal.findMatchHighlightBackground" = "#39393999"
"terminal.findMatchHighlightBorder" = "#39393999"
"terminal.hoverHighlightBackground" = "#39393999"
"terminalCursor.background" = "#161616"
"terminalCursor.foreground" = "#ffffff"

"symbolIcon.arrayForeground" = "#ffffff"
"symbolIcon.booleanForeground" = "#ffffff"
"symbolIcon.classForeground" = "#ffffff"
"symbolIcon.constantForeground" = "#ffffff"
"symbolIcon.constructorForeground" = "#ffffff"
"symbolIcon.enumeratorForeground" = "#ffffff"
"symbolIcon.fieldForeground" = "#ffffff"
"symbolIcon.functionForeground" = "#ffffff"
"symbolIcon.interfaceForeground" = "#ffffff"
"symbolIcon.keyForeground" = "#ffffff"
"symbolIcon.keywordForeground" = "#ffffff"
"symbolIcon.methodForeground" = "#ffffff"
"symbolIcon.moduleForeground" = "#ffffff"
"symbolIcon.namespaceForeground" = "#ffffff"
"symbolIcon.numberForeground" = "#ffffff"
"symbolIcon.objectForeground" = "#ffffff"
"symbolIcon.operatorForeground" = "#ffffff"
"symbolIcon.packageForeground" = "#ffffff"
"symbolIcon.propertyForeground" = "#ffffff"
"symbolIcon.stringForeground" = "#ffffff"
"symbolIcon.structForeground" = "#ffffff"
"symbolIcon.typeParameterForeground" = "#ffffff"
"symbolIcon.variableForeground" = "#ffffff"

[[tokenColors]]
scope = ["comment"]
settings = { foreground = "#6f6f6f" }

[[tokenColors]]
scope = ["entity"]
settings = { foreground = "#dde1e6" }

[[tokenColors]]
scope = ["storage.modifier.package", "storage.modifier.import"]
settings = { foreground = "#f2f4f8" }

[[tokenColors]]
scope = ["variable"]
settings = { foreground = "#ffffff" }

[[tokenColors]]
scope = ["support"]
settings = { foreground = "#08bdba" }

[[tokenColors]]
scope = [
    "storage.type",
    "keyword.other.fn",
    "keyword.operator",
    "punctuation.separator",
    "punctuation.definition.tag",
    "punctuation.definition.list",
    "variable.other.constant.singlequote",
    "variable.other.constant.backquote",
    "variable.other.constant.sharpsign",
]
settings = { foreground = "#3ddbd9" }

[[tokenColors]]
scope = ["keyword"]
settings = { foreground = "#78a9ff" }

[[tokenColors]]
scope = ["storage.modifier", "keyword.other"]
settings = { foreground = "#33b1ff" }

[[tokenColors]]
scope = ["entity.name.function", "storage.type.function.m.nosideeffects"]
settings = { foreground = "#ff7eb6" }

[[tokenColors]]
scope = ["string"]
settings = { foreground = "#be95ff" }

[[tokenColors]]
scope = ["constant"]
settings = { foreground = "#82cfff" }

# styles

# [[tokenColors]]
# scope = ["entity.name.type"]
# settings = { fontStyle = "underline" }

[[tokenColors]]
scope = ["entity.name.function", "variable.other.definition"]
settings = { fontStyle = "bold" }

[[tokenColors]]
scope = ["storage.type", "variable.parameter"]
settings = { fontStyle = "italic" }

# C
[[tokenColors]]
scope = ["keyword.control.directive"]
settings = { foreground = "#08bdba" }

# Rust
[[tokenColors]]
scope = ["storage.type.rust"]
settings = { foreground = "#78a9ff" }

# Go
[[tokenColors]]
scope = ["entity.name.import.go"]
settings = { foreground = "#be95ff" }

# Lisp
[[tokenColors]]
scope = ["support.function.f.sideeffects"]
settings = { foreground = "#ee5396" }

# Verilog
[[tokenColors]]
scope = ["entity.name.type.module.verilog"]
settings = { foreground = "#ee5396" }

[[tokenColors]]
scope = ["entity.name.tag.module.identifier"]
settings = { foreground = "#08bdba" }

[[tokenColors]]
scope = ["entity.name.tag.module.reference"]
settings = { foreground = "#ff7eb6", fontStyle = "bold" }

# Markdown
[[tokenColors]]
scope = ["entity.name.section.markdown", "markup.inline.raw.string.markdown"]
settings = { foreground = "#ffffff", fontStyle = "bold" }

[[tokenColors]]
scope = ["punctuation.definition.heading.markdown"]
settings = { foreground = "#ff7eb6" }

[[tokenColors]]
scope = [
    "punctuation.definition.raw.markdown", 
    "punctuation.definition.markdown"
]
settings = { foreground = "#08bdba" }
